#!/bin/bash
set -e

ROOT=$(pwd)

export PYRAMID_SETTINGS="production.ini#main"

# intialize the app
cd service
python setup.py develop
cd ${ROOT}

# compile project
cd service
make clean
make build
cd ${ROOT}

# run the app
python runapp.py
